// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwrmeiucnfqfamzsmksr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cm1laXVjbmZxZmFtenNta3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzAxNzAsImV4cCI6MjA1MzE0NjE3MH0.KmgARQ5REkgtK81IwNYR1enfJDVYXDwzx82wnQWU8vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);